spring.application.name=Java Community AI Assistant
server.port=8080

spring.datasource.url=jdbc:oracle:thin:@aidbcommunityassistent_low?TNS_ADMIN=${WALLET_PATH}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

oci.config.path=${OCI_CONFIG_PATH:~/.oci/config}
oci.config.profile=${OCI_PROFILE:DEFAULT}

oci.tenant.id=${OCI_TENANT_ID}
oci.compartment.id=${OCI_COMPARTMENT_ID}
oci.region=sa-saopaulo-1

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
